---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure HBAC Rule allhosts is present
    freeipa.ansible_freeipa.ipahbacrule:
      ipaadmin_password: SomeADMINpassword
      name: allhosts
      usercategory: all
